### PR TITLE
Add edit action to admin grids

### PR DESCRIPTION
**Pull request by fredden**
This pull request adds an 'edit' action to each of the four admin grids. This action goes to the relevant product/category at the indicated store view, allowing an administrator to make changes to the product/category in question.

### CODE REVIEW

**Comment by hostep** [comment]
Awesome, that sounds like a great idea!

Give me a few days to review and test, but I think a new version will appear within a week or so with this included 🙂

**Comment by fredden** [comment]
Feel free to adapt to meet your requirements or ask for changes.

**Comment by hostep** [comment]
I've start applying some updates [over here](https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/commits/edit-link), haven't figured out yet how I'm able to update this PR in github itself with my updated code, but I'll try to make sure your commits get included when everything gets merged.

**Comment by fredden** [comment]
Thanks for the update. I expect you'd be able to push to my fork / this branch: https://github.com/fredden/baldwin-magento2-module-url-data-integrity-checker/tree/edit-link. I've also tried to add you as a collaborator on my fork to see if that helps with permissions. (I don't know how the GitHub permissions work in this case.)

Meanwhile, I've pulled in your changes to this branch.

**Comment by hostep** [comment]
This has now been published in [version 1.5.0](https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/releases/tag/v1.5.0) of this module, thank you very much! 🙂

**Pull request merged**
