### PR TITLE
Github actions - ease testing and configurable path

### PR DESCRIPTION
**Pull request by DominicWatts**
I installed in a multi-container environment and the tmp var was not mounted and therefore was not shared between containers. I recommend that you allow the path of the json files to be configurable.

Also I took the time to create github actions based on your Makefile. Easier to test code submissions.

### CODE REVIEW

**Comment by DominicWatts** [comment]
You can see example test results here

https://github.com/DominicWatts/magento2-module-url-data-integrity-checker/actions

**Comment by DominicWatts** [comment]
I've put some keys in the actions - so they are publicly visible. However you can use github secrets

https://github.com/DominicWatts/Faker/blob/master/.github/workflows/phpstan.yml#L10

```
- uses: MilesChou/composer-action@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
```

But that needs configuring in each repo

Anyway, worse case scenario I hope you consider the introduction of a configurable path.

**Comment by hostep** [comment]
Thanks @DominicWatts!

Will try to have a proper look in one of the next few weeks. But first remark would be if you could split the PR into two parts, where the new functionality is added in one PR, and the github actions are in a second PR.

**Comment by DominicWatts** [comment]
No probs - created two PRs

https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/pull/28

https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/pull/29

**Pull request closed without merging**
